#!/usr/bin/env bash

macos_setup() {
  # inspired by https://mths.be/macos
  defaults write com.apple.dock persistent-apps -array
  defaults write com.apple.dock autohide -boolean true
  defaults write com.apple.dock orientation -string left

  defaults write com.apple.menuextra.clock DateFormat -string 'EEE MMM d H:mm'

  defaults write NSGlobalDomain AppleKeyboardUIMode -int 3 # enable full keyboard access
  # appers not to work in high sierra / 10.13
  defaults write NSGlobalDomain com.apple.keyboard.fnState -boolean true  # enable function keys
}

# Homebrew
export HOMEBREW_NO_ANALYTICS=1 # Turn of homebrew data collection
export HOMEBREW_NO_INSECURE_REDIRECT=1 # Disallow `https` => `http` redirects

bup() {
  # we don't force cleanup, just advise on whats different
  brew update && \
    brew bundle cleanup --global && \
    brew bundle --global && \
    brew upgrade && brew cask upgrade && \
    brew cleanup && \
    brew doctor ; brew cask doctor
}

source "${HOME}/.bashrc"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"

# Iterm 2 shell integration (if installed)
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

